# Generated by Django 4.1.2 on 2022-11-05 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PetsitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Warszawa', max_length=120)),
                ('address', models.CharField(max_length=164)),
                ('place_type', models.IntegerField(choices=[(0, 'MIESZKANIE'), (1, 'DOM')], default=0)),
                ('transport', models.BooleanField(default=False)),
                ('about', models.TextField(max_length=500)),
                ('animals', models.ManyToManyField(to='PetsitUser.animal')),
                ('size', models.ManyToManyField(to='PetsitUser.animalsize')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
