# Generated by Django 4.1.2 on 2022-11-05 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PetsitUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('message', models.TextField(max_length=500, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetsitUser.animal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_ordered', to=settings.AUTH_USER_MODEL)),
                ('pet_sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_care', to=settings.AUTH_USER_MODEL)),
                ('size', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PetsitUser.animalsize')),
            ],
        ),
    ]
